[[redirects]]
  from = "/*"
  to = "/error"
  status = 404

[[redirects]]
  from = "/"
  to = "/contact"
  status = 301
  force = false

[build]
    functions = "functions/"
    command = "npm run build"
    publish = "build"